// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_dvEmjhiB-xPDnMG91dRgAt5eABIYfnQ',
    appId: '1:644417397860:web:e344738c856a8cc19b6b71',
    messagingSenderId: '644417397860',
    projectId: 'cn333-95dd5',
    authDomain: 'cn333-95dd5.firebaseapp.com',
    storageBucket: 'cn333-95dd5.firebasestorage.app',
    measurementId: 'G-HHTWJ3L0X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDewhT8EfoEb91Xlk3ovF4lgw6SA790HC8',
    appId: '1:644417397860:android:d84d76b81ed87f7d9b6b71',
    messagingSenderId: '644417397860',
    projectId: 'cn333-95dd5',
    storageBucket: 'cn333-95dd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfhY2YktuBxk-HcIzRPlM1SXQ61IOyVlY',
    appId: '1:644417397860:ios:f74da698e7c1e8fa9b6b71',
    messagingSenderId: '644417397860',
    projectId: 'cn333-95dd5',
    storageBucket: 'cn333-95dd5.firebasestorage.app',
    iosBundleId: 'com.example.rushpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfhY2YktuBxk-HcIzRPlM1SXQ61IOyVlY',
    appId: '1:644417397860:ios:f74da698e7c1e8fa9b6b71',
    messagingSenderId: '644417397860',
    projectId: 'cn333-95dd5',
    storageBucket: 'cn333-95dd5.firebasestorage.app',
    iosBundleId: 'com.example.rushpal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_dvEmjhiB-xPDnMG91dRgAt5eABIYfnQ',
    appId: '1:644417397860:web:6af42c6e1c122c899b6b71',
    messagingSenderId: '644417397860',
    projectId: 'cn333-95dd5',
    authDomain: 'cn333-95dd5.firebaseapp.com',
    storageBucket: 'cn333-95dd5.firebasestorage.app',
    measurementId: 'G-VNHER5ENT6',
  );
}